# Generated by Django 4.2.6 on 2024-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0002_product_fssai_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='app/static/images'),
        ),
        migrations.AlterField(
            model_name='product2',
            name='image',
            field=models.ImageField(upload_to='app/static/images'),
        ),
        migrations.AlterField(
            model_name='product2',
            name='image2',
            field=models.ImageField(upload_to='app/static/images'),
        ),
    ]
