# Generated by Django 4.2.6 on 2024-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
