# Generated by Django 4.2.6 on 2024-03-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='FlatNumber',
            field=models.CharField(default='a', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='Landmark',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
