# Generated by Django 4.2.6 on 2024-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0013_remove_order_image_order_flatnumber_order_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='img/category-1.jpg', upload_to='static/img/'),
        ),
    ]
