# Generated by Django 4.2.6 on 2024-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0014_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PL', 'Placed'), ('PC', 'Picked Up'), ('OT', 'Out for Delivery'), ('DL', 'Delivered'), ('CA', 'Cancelled')], default='PL', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
