# Generated by Django 4.2.6 on 2024-04-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0016_remove_order_image_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Landmark',
            new_name='landmark',
        ),
    ]
