# Generated by Django 4.2.6 on 2024-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0021_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='products',
            field=models.ManyToManyField(to='groceryapp.product2'),
        ),
        migrations.AlterField(
            model_name='details',
            name='delivery_boy',
            field=models.CharField(choices=[('pending', 'Pending'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='ram', max_length=50),
        ),
    ]
