# Generated by Django 4.2.6 on 2024-04-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0022_details_products_alter_details_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='details',
            name='products',
        ),
        migrations.RemoveField(
            model_name='details',
            name='user',
        ),
    ]
